
spring:
  application:
    name: microservicio-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
            - 'http://localhost:4200'
            allowed-headers:
            - Content-Type
            allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE 
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true
      routes:
      - id: microservicio-usuarios
        uri: lb://microservicio-usuarios
        predicates:
        - Path=/api/alumnos/**
        filters:
        - StripPrefix=2
      - id: microservicio-cursos
        uri: lb://microservicio-cursos
        predicates:
        - Path=/api/cursos/**
        filters:
        - StripPrefix=2
      - id: microservicio-examenes
        uri: lb://microservicio-examenes
        predicates:
        - Path=/api/examenes/**
        filters:
        - StripPrefix=2
      - id: microservicio-respuestas
        uri: lb://microservicio-respuestas
        predicates:
        - Path=/api/respuestas/**
        filters:
        - StripPrefix=2
server:
 port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

        
